#!/usr/bin/env ruby

require "chingu"

Dir["#{File.dirname(__FILE__)}/lib/*.rb"].each {|f| require f}
include Gosu
include Chingu

class Game < Chingu::Window
  def initialize
    super(800, 600, false)
  end    

  def setup
      retrofy
      self.factor = 1
      switch_game_state(Pirates.new)
  end
end

class Pirates < GameState
    def initialize(options = {})
        super

        $window.caption = "A Game of Pirates"

        self.input = { :escape => :end_game }

        @deaths = 0
        @prisoner_count = 0

        @sea = Sea.create(:zorder => 10)

        @islands = Islands.new(:game_objects => {})

        min_size = 5
        for i in (0..5) do
            @islands.add_map(Island.new(:game_objects => {}, :island_size => min_size + rand(25)))
        end

        @player = Player.create(:x => rand($window.width), :y => rand($window.height))
        while (@islands.occupied?(@player))
            @player = Player.create(:x => rand($window.width), :y => rand($window.height))
        end

        @player.input = {
            :holding_left => :steer_left, 
            :holding_right => :steer_right,
            :holding_up => :move_forward,
            :space => :fire_cannon
        }

        @galleon = Galleon.create(
            :x => rand($window.width),
            :y => rand($window.height),
            :max_velocity => 10
        )
        while (@islands.occupied?(@galleon))
            @galleon = Galleon.create(
                :x => rand($window.width),
                :y => rand($window.height),
                :max_velocity => 10
            )
        end

    end

    def update
        super

        # Collisions
        Galleon.each_collision(Bullet) do |galleon, bullet|
            galleon.destroy
            bullet.destroy
        end

        @bullets = game_objects_of_class(Bullet)

        @bullets.each do |bullet|

            if ! @galleon.nil? && @galleon.collides?(bullet)
                p "Hit"
                @galleon.destroy
                @galleon = nil
                bullet.destroy
                break
            elsif @player.collides? bullet
                puts "YOU WERE STRUCK!"
                end_game
            end
        end

        @islands.map.each do |object|
            if object.is_a? IslandTile

                if @player.collides?(object)
                    @deaths += 1
                    end_game
                elsif !@galleon.nil? && @galleon.collides?(object)

                    @galleon.reverse 
                    break;
                end

                if object.is_a? House
                    @bullets.each do |bullet|
                        if object.collides?(bullet)
                            @prisoner_count += object.capture
                            object.pause!
                            object.destroy
                            break;
                        end
                    end
                end
            end
        end
    end

    def draw
        border_x = {:min => 0, :max => $window.width }
        border_y = { :min => 0, :max => $window.height }

        for i in (0..($window.width/@sea.width + 1)) do
            for j in (0..($window.height/@sea.height + 1)) do
                @sea.x = i * @sea.width
                @sea.y = j * @sea.height
                @sea.draw
            end
        end


        @islands.draw

        @player.draw

        # Enemy
        @galleon.draw if !@galleon.nil?

        game_objects_of_class(Bullet).each do |cannon_ball|
            cannon_ball.draw
        end
    end

    def end_game
        puts "You Trapped #{@prisoner_count} villagers!"
        close

       switch_game_state(EndState.new(:prisoner_count => @prisoner_count))
    end
end

class EndState < GameState

    def initialize(options = {})
        super(options)
        $window.caption = "A Game of Pirates: You Lost"

        self.input = { :escape => :exit }

        x_offset = $window.width / 3 
        Text.create("You Lost",
             :x => x_offset,
             :y => 100,
             :size => 40,
             :align => :center
        )

        Text.create("You captured: #{options[:prisoner_count]} villagers!",
             :x => x_offset,
             :y => 300,
             :size => 30,
             :align => :center
        )

        Text.create("Press <ESC> to exit",
             :x => x_offset,
             :y => 500,
             :align => :center
        )
    end

    def draw
        super
    end
end

# Start the Game
Game.new.show
